#Requires -Version 5.1
<#
.SYNOPSIS
    MCP Trust Anchor - Windows Client Bootstrap

.DESCRIPTION
    Installs the MCP Bridge and Subscriber Node components for Claude Code/Desktop.
    Configures Claude to use the secure tool execution framework.

.PARAMETER TrustAnchorUrl
    URL of the Trust Anchor server (default: http://localhost:8000)

.PARAMETER InstallDir
    Installation directory (default: C:\Program Files\MCP-Trust-Anchor)

.PARAMETER SkipClaudeConfig
    Skip automatic Claude Desktop/Code configuration

.EXAMPLE
    .\bootstrap.ps1 -TrustAnchorUrl "http://192.168.1.100:8000"

.EXAMPLE
    .\bootstrap.ps1 -InstallDir "C:\Tools\MCP"
#>

[CmdletBinding()]
param(
    [string]$TrustAnchorUrl = "http://localhost:8000",
    [string]$InstallDir = "$env:ProgramFiles\MCP-Trust-Anchor",
    [switch]$SkipClaudeConfig,
    [switch]$Force
)

$ErrorActionPreference = "Stop"

# Colors
function Write-Success { Write-Host $args -ForegroundColor Green }
function Write-Warning { Write-Host $args -ForegroundColor Yellow }
function Write-Error { Write-Host $args -ForegroundColor Red }
function Write-Info { Write-Host $args -ForegroundColor Cyan }

Write-Host ""
Write-Host "======================================" -ForegroundColor Green
Write-Host "MCP Trust Anchor - Client Bootstrap" -ForegroundColor Green
Write-Host "======================================" -ForegroundColor Green
Write-Host ""

# Step 1: Check Python
Write-Info "[1/6] Checking Python installation..."
$pythonCmd = $null
foreach ($cmd in @("python", "python3", "py -3")) {
    try {
        $version = & $cmd.Split()[0] $cmd.Split()[1..99] --version 2>&1
        if ($version -match "Python 3\.1[0-9]") {
            $pythonCmd = $cmd
            Write-Host "  Found: $version"
            break
        }
    } catch {}
}

if (-not $pythonCmd) {
    Write-Error "  Python 3.10+ not found!"
    Write-Host "  Please install Python from: https://www.python.org/downloads/"
    exit 1
}

# Step 2: Create directories
Write-Info "[2/6] Creating directories..."
$dirs = @(
    $InstallDir,
    "$InstallDir\mcp_bridge",
    "$InstallDir\subscriber_node",
    "$InstallDir\subscriber_node\crypto",
    "$InstallDir\logs",
    "$env:USERPROFILE\.config\mcp"
)

foreach ($dir in $dirs) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
        Write-Host "  Created: $dir"
    }
}

# Step 3: Copy client files
Write-Info "[3/6] Copying client files..."
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

# Copy MCP Bridge
Copy-Item "$scriptDir\mcp_bridge\*" "$InstallDir\mcp_bridge\" -Recurse -Force
Write-Host "  Copied: mcp_bridge"

# Copy Subscriber Node
Copy-Item "$scriptDir\subscriber_node\*" "$InstallDir\subscriber_node\" -Recurse -Force
Write-Host "  Copied: subscriber_node"

# Step 4: Create virtual environment and install dependencies
Write-Info "[4/6] Setting up Python environment..."
$venvDir = "$InstallDir\venv"

if (-not (Test-Path "$venvDir\Scripts\activate.ps1") -or $Force) {
    Write-Host "  Creating virtual environment..."
    & $pythonCmd.Split()[0] $pythonCmd.Split()[1..99] -m venv $venvDir
}

# Activate and install
& "$venvDir\Scripts\pip.exe" install --upgrade pip wheel | Out-Null
& "$venvDir\Scripts\pip.exe" install httpx pyyaml cryptography mcp | Out-Null
Write-Host "  Dependencies installed"

# Step 5: Create configuration
Write-Info "[5/6] Creating configuration..."

# MCP Bridge config
$configContent = @"
# MCP Trust Anchor Client Configuration
# Generated by bootstrap.ps1

TRUST_ANCHOR_URL=$TrustAnchorUrl
CREDENTIAL_PATH=$env:USERPROFILE\.config\mcp
LOG_LEVEL=INFO
"@

$configContent | Out-File -FilePath "$InstallDir\config.env" -Encoding UTF8
Write-Host "  Config: $InstallDir\config.env"

# Create sample credential template
$credTemplate = @"
# FortiGate Credentials Template
# Copy to: ~/.config/mcp/fortigate_credentials.yaml

devices:
  my-fortigate:
    host: "192.168.1.1"
    api_token: "YOUR_API_TOKEN_HERE"
    verify_ssl: false

# Map IPs to device names for automatic lookup
default_lookup:
  "192.168.1.1": "my-fortigate"
"@

$credPath = "$env:USERPROFILE\.config\mcp\fortigate_credentials.yaml.template"
if (-not (Test-Path $credPath.Replace(".template", ""))) {
    $credTemplate | Out-File -FilePath $credPath -Encoding UTF8
    Write-Host "  Credential template: $credPath"
}

# Step 6: Configure Claude Desktop/Code
Write-Info "[6/6] Configuring Claude integration..."

if ($SkipClaudeConfig) {
    Write-Host "  Skipped (--SkipClaudeConfig)"
} else {
    # Claude Desktop config location
    $claudeConfigDir = "$env:APPDATA\Claude"
    $claudeConfigPath = "$claudeConfigDir\claude_desktop_config.json"

    # Create MCP server configuration
    $mcpServerConfig = @{
        "secure-tools" = @{
            "command" = "$venvDir\Scripts\python.exe"
            "args" = @(
                "$InstallDir\mcp_bridge\MCP-secure-tools-server.py"
            )
            "env" = @{
                "TRUST_ANCHOR_URL" = $TrustAnchorUrl
                "CREDENTIAL_PATH" = "$env:USERPROFILE\.config\mcp"
            }
        }
    }

    # Check if Claude config exists
    if (Test-Path $claudeConfigPath) {
        Write-Host "  Found existing Claude config"
        $claudeConfig = Get-Content $claudeConfigPath | ConvertFrom-Json -AsHashtable

        if (-not $claudeConfig.mcpServers) {
            $claudeConfig.mcpServers = @{}
        }

        # Add our server
        $claudeConfig.mcpServers["secure-tools"] = $mcpServerConfig["secure-tools"]

        $claudeConfig | ConvertTo-Json -Depth 10 | Out-File $claudeConfigPath -Encoding UTF8
        Write-Host "  Updated: $claudeConfigPath"
    } else {
        # Create new config
        if (-not (Test-Path $claudeConfigDir)) {
            New-Item -ItemType Directory -Path $claudeConfigDir -Force | Out-Null
        }

        $newConfig = @{
            "mcpServers" = $mcpServerConfig
        }

        $newConfig | ConvertTo-Json -Depth 10 | Out-File $claudeConfigPath -Encoding UTF8
        Write-Host "  Created: $claudeConfigPath"
    }
}

# Done
Write-Host ""
Write-Success "Installation Complete!"
Write-Host ""
Write-Host "Installation directory: $InstallDir"
Write-Host "Trust Anchor URL: $TrustAnchorUrl"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Configure credentials: $env:USERPROFILE\.config\mcp\fortigate_credentials.yaml"
Write-Host "  2. Restart Claude Desktop to load the MCP server"
Write-Host "  3. Test: Ask Claude 'list available tools'"
Write-Host ""
Write-Host "To test manually:"
Write-Host "  & '$venvDir\Scripts\python.exe' '$InstallDir\mcp_bridge\MCP-secure-tools-server.py'"
Write-Host ""

# Quick connectivity test
Write-Info "Testing Trust Anchor connectivity..."
try {
    $response = Invoke-WebRequest -Uri "$TrustAnchorUrl/health" -UseBasicParsing -TimeoutSec 5
    if ($response.StatusCode -eq 200) {
        Write-Success "  Trust Anchor is reachable!"
    }
} catch {
    Write-Warning "  Could not reach Trust Anchor at $TrustAnchorUrl"
    Write-Host "  Make sure the server is running and accessible"
}
